// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRbbHOsbqE-OvWG3MoByQoWPWoe6tOxc',
    appId: '1:1039776702029:web:171189adefa24c90648604',
    messagingSenderId: '1039776702029',
    projectId: 'helth-8c065',
    authDomain: 'helth-8c065.firebaseapp.com',
    storageBucket: 'helth-8c065.appspot.com',
    measurementId: 'G-PGPXZQ345C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNdGiuSJLbt0bAw6Q6qufCp8E3iP39VkY',
    appId: '1:1039776702029:android:f88916b0aef15b3e648604',
    messagingSenderId: '1039776702029',
    projectId: 'helth-8c065',
    storageBucket: 'helth-8c065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsO4zT0gnyiym7IimPeftVhHGobh4JWE',
    appId: '1:1039776702029:ios:b52c6488bd6504fd648604',
    messagingSenderId: '1039776702029',
    projectId: 'helth-8c065',
    storageBucket: 'helth-8c065.appspot.com',
    iosBundleId: 'com.example.health',
  );
}
